### ISSUE TITLE
São Paulo - SP; tempo indeterminado

### ISSUE THREAD

**Issue by woliveiras** [training-center/code-house#1]
## Procuro um local para morar

[São Paulo][SP][Tempo indeterminado]

Pessoas, busco quarto individual próximo a Av. Paulista ou próximo a Metrôs de fácil acesso a essa região.

Não fumo, não bebo, não faço bagunça em casa e gosto de animais (caso você tenha algum e queira dividir com alguém que também curta os bixin), passo a maior parte do tempo no computador estudando e por isso vai ser difícil se incomodar com a minha presença.

Não tenho restrição contra fumantes ou beberrões, viu. 🤣 🤣

Quem dividir apartamento comigo ganha de bônus minhas principais habilidades: cozinhar ovo, fritar ovo, fazer ovo pro jantar e miojo nas mais variadas receitas especiais.

Sou desenvolvedor Front End e posso te ajudar nisso (HTML, CSS, JavaScript e todo o eco sistema dessas tecnologias).

[INFORMAÇÕES SOBRE O QUE PRECISO NO LOCAL]

Só preciso de um quarto individual e precisamos de um link de internet, afinal trabalhamos com tecnologia e as vezes trabalho de casa.

[RESTRIÇÕES]

Apesar de não ter restrições contra fumantes ou beberrões, não gostaria de limpar sujeira de alguém que encheu demais a cara, ein...

Redes Sociais:

- https://www.facebook.com/woliveira542
- https://twitter.com/w_oliveiras

**Comment by 88patota** [comment]
> cozinhar ovo, fritar ovo, fazer ovo pro jantar e miojo...

HAHAHA

**Comment by woliveiras** [comment]
To falando mano... Miojão monstro!

**Comment by ederchristian** [comment]
Cara, legal. Também tenho o perfil bem parecido com o teu e também busco um espaço (quarto individual) nessa região de São Paulo, mas se for perto do metrô Fradique Coutinho melhor ainda!

E também estou buscando um espaço na faixa de preço que você procura.

Com certeza passarei boa parte do tempo estudando no quarto e vez ou outra irei a algum meetup ou algum evento.


Twitter: https://twitter.com/ederchristian92
E-mail: ederchristian92@gmail.com

**Comment by woliveiras** [comment]
Vou te mandar email, mano! :D

**Comment by woliveiras** [comment]
Tive uma mudança de planos na vida e por isso vou fechar a issue, galera.
