### ISSUE TITLE
Devemos manter este projeto?

### ISSUE THREAD

**Issue by woliveiras** [training-center/code-house#10]
Este repositório está parado a algum tempo.

Não estamos conseguindo manter o projeto ativo.

Devemos realmente manter a ideia aberta?

**Comment by jgcmarins** [comment]
Na minha visão, este repositório tem muito valor sim.
O que é necessário para manter o projeto ativo?
Acredito que posso ajudar vocês a mantê-lo.

**Comment by danilosilvadev** [comment]
Eu quero que continue até eu ir pra sp pelo menos rsrs pq eu quero dividir ap com um/uma coder.

**Comment by jgcmarins** [comment]
Pontos pra melhorar?
- [ ] divulgar?
- [ ] incentivar a galera a ativar o watch?

**Comment by woliveiras** [comment]
Acredito que precisamos arrumar uma maneira de divulgar mais, realmente incentivar o pessoal a dar o watch (talvez fazer igual no [forum](https://github.com/training-center/forum/#como-receber-atualizações-do-forum)) e coletar feedback de quem está enviando issues.

Se puder se envolver para ajudar, será muito bom, @jgcmarins.

**Comment by danilosilvadev** [comment]
@woliveiras lance é que mudança n é uma coisa q a gente faz td dia. Então o público geral já é nichado dos que estão se mudando. Além do mais passa por outro filtro que é de ser programadores. Esse repo sempre vai ser paradão acredito, a menos que não fosse só pra programadores e sim pra qualquer tipo de profissional e fosse tipo um app. No formato atual o público é pequeno. Mas não encaro isso como um problema, quem precisar vai usando e tals. Divulgar, podemos sempre divulgar num artigo ou outro, numa live, no slack e tals com os times de divulgação.

**Comment by woliveiras** [comment]
@danilosilvadev mandou uma opinião muito importante! 

Concordo contigo. Realmente aqui nunca será tão movimentado quanto os outros repositórios.

Você é fera, meu rei! 

Acredito que, com essa argumentação, podemos fechar a issue e manter o repositório.

**Comment by gnumoksha** [comment]
Concordo com o @jgcmarins  e @danilosilvadev.

Meus $0.02 sobre possíveis melhorias:
* `Diminuir o texto do README.md.` Há muito texto que pode não ser necessário a primeira vista. Texto demais nos remete a complexidade/burocracia e diminuiu o engajamento do usuário. Creio que o tamanho ideal é algo como o do [frontendbr/vagas](https://github.com/frontendbr/vagas/). Informaçoes extras podem ser colocadas em outros *.md ou wiki e serem linkados no README.md
* `Reforçar o uso do slack ou canais privados para chat` de modo que os interessados não precisem expor mais informações do que necessário/gostariam em issues públicas no Github (talvez deixar o template de issues mais sucinto?)
* `Estudar maneiras de divulgar este projeto`. A ideia é otima, mas o acesso a ela não é tão simples/intuitivo quanto uma pesquisa no Google. O que podemos fazer para nos deixar mais perto deste objetivo? Talvez fazermos posts no medium, em comunidades de facebook, listas de email e tweets ? Montar um hotsite (com github pages) para cair nas pesquisas do Google?

**Comment by woliveiras** [comment]
Fala, galera!

Tivemos ótimos comentários nessa issue.

Obrigado pelas sugestões!
