### ISSUE TITLE
Porto Alegre (BrazilJS)

### ISSUE THREAD

**Issue by joaopjt** [training-center/code-house#2]
## Procuro um local para dormir

[Porto Alegre][RS][4 - 5 dias]

Olá, me chamo João, moro em Franca-SP, e vou para a BrazilJS em uma turma de 4 pessoas. Trabalhamos todos com desenvolvimento web na mesma empresa, e vamos para o evento, chegando Quarta-feira à noite (23 de agosto).

Precisamos de cama (individuais, se possível), internet e de preferência, um local nas redondezas ao evento.

Não temos nenhuma restrição especifica, a não ser com a questão de silencio à noite, o evento é cansativo e precisamos descansar.

Meu facebook: http://fb.com/joaopjt

**Comment by nicholasess** [comment]
@woliveiras pode fechar
