### ISSUE TITLE
São Paulo - SP | Julho de 2017

### ISSUE THREAD

**Issue by jgcmarins** [training-center/code-house#3]
## Procuro um local para morar

[São Paulo][SP][Julho de 2017]

Sou estudante de Ciências de Computação e estou indo pra São Paulo fazer estágio de férias. Atualmente moro em São Carlos, mas me viro bem na capital. Aqui em São Carlos eu já dividi apê e também fundei uma república. Sei bem como é dividir moradia. Ficarei muito feliz se encontrar um lugar pra ficar através deste canal. Curto animais, fazer comida e conversar!

[INFORMAÇÕES SOBRE O QUE PRECISO NO LOCAL]
- Ser próximo à região do Brooklin
- Internet (ah vá, hahaha)
- Uma cama
- Um fogão (To sem grana pra ficar comendo fora)
- Geladeira

[RESTRIÇÕES]
Em geral não tenho nenhuma restrição, mas seria bacana ter uma cozinha em condições de uso. Diariamente, hahahaha

[LINKS PARA REDES SOCIAIS] 
- [Facebook](https://www.facebook.com/jgcmarins)
- [Twitter](https://twitter.com/jgcmarins)

**Comment by jgcmarins** [comment]
Thanks, @vicainelli

**Comment by woliveiras** [comment]
Já compartilhe essa issue nos grupos possíveis @jgcmarins

**Comment by jgcmarins** [comment]
@woliveiras muito obrigado!!!

**Comment by Vitao18** [comment]
Já conseguiu?
Se quiser trocar uma ideia, manda mensagem :)

**Comment by jgcmarins** [comment]
@Vitao18 ainda não. Manda msg no meu [facebook](https://www.facebook.com/jgcmarins), por favor. Valeu!
