### ISSUE TITLE
São Paulo - SP | O quanto antes e por tempo indeterminado

### ISSUE THREAD

**Issue by jgcmarins** [training-center/code-house#5]
## Procuro um local para morar

SÃO PAULO, SP - Por tempo indeterminado

Sou estudante de Ciências de Computação e estou indo pra São Paulo trabalhar e terminar a faculdade. Atualmente moro em São Carlos, mas me viro bem na capital. Aqui em São Carlos eu já dividi apê e também fundei uma república. Sei bem como é dividir moradia. Ficarei muito feliz se encontrar um lugar pra ficar através deste canal. Curto animais, fazer comida e conversar!

[INFORMAÇÕES SOBRE O QUE PRECISO NO LOCAL]
- Ser próximo à região do Brooklin
- Internet (ah vá, hahaha)
- Uma cama
- Um fogão (To sem grana pra ficar comendo fora)
- Geladeira

[RESTRIÇÕES]
Em geral não tenho nenhuma restrição, mas seria bacana ter uma cozinha em condições de uso. Diariamente, hahahaha

[LINKS PARA REDES SOCIAIS] 
- [Facebook](https://www.facebook.com/jgcmarins)
- [Twitter](https://twitter.com/jgcmarins)

**Comment by Vitao18** [comment]
Acabei de te chamar no Face!!

**Comment by liperama-dev** [comment]
Também te mandei uma mensagem!

**Comment by jgcmarins** [comment]
Encontrei! Thanks 😄

**Comment by woliveiras** [comment]
Show de bola, @jgcmarins 

Vou entrar em contato contigo no Face para trocar ideia sobre sua experiência aqui no projeto.
