### ISSUE TITLE
[SÃO PAULO][SP][INDETERMINADO][VALOR][Consigo pagar até R$1.000,00]

### ISSUE THREAD

**Issue by lucasmarques73** [training-center/code-house#6]
## Procuro um local para morar ou dividir Moradia

[SÃO PAULO][SP][INDETERMINADO][VALOR][Consigo pagar até R$1.000,00]

Meu nome é Lucas, atualmente moro no interior de Minas, precisamente em Passos/MG, recentemente participei de um processo seletivo para uma empresa de São Paulo e consegui, me chamaram pra ir e agora busco um local para morar lá. Tenho 24 anos, gosto de animais, sou Corinthiano mas não sou aquelas que brigam por causa de futebol, podem ficar tranquilos. Sou sociável, gosto de tomar uma cerveja de vez em quando. 

[INFORMAÇÕES SOBRE O QUE PRECISO NO LOCAL] 
Preciso de algo próximo à metro, o local onde vou trabalhar é entre os metrôs Ana Rosa e Vila Mariana. Procuro algo já mobiliado pois ainda não tenho muita coisa e não vou conseguir levar nada de Passos para SP. Além da mobília, internet é indispensável hahaha.

[RESTRIÇÕES] 
Tenho alguns problemas respiratórios, então, se você fuma, pediria que fosse fora do ambiente de convívio nosso.

[LINKS PARA REDES SOCIAIS]
https://www.facebook.com/lucasmarques73
https://www.linkedin.com/in/lucasmarques73/

**Comment by gnumoksha** [comment]
Conseguiu, @lucasmarques73 ?

**Comment by lucasmarques4linux** [comment]
@gnumoksha Estou morando em SP.. dividindo apartamento.. Mas estou sempre buscando algo melhor.. Atualmente moro próximo no metrô São Judas.. E onde eu moro ta com vaga pra solteiro.. Rua Professor Aprigio Gonzaga 700.. Atualmente moramos eu, minha namorada e mais um.. Este é o anúncio dele.
https://www.easyquarto.com.br/saude-companheiros-de-quarto/vaga-ap-mobiliado-prox-metro-sao-judas/H171005205234246

Mas se você animar podemos trocar ideia e a gnt ve de alugar algo tb..

**Comment by gnumoksha** [comment]
@lucasmarques4linux obrigado pela resposta. Tenho interesse. Hoje moro perto da Ana Rosa, porém estou mudando de emprego e preciso levar em consideração a localização da moradia.

**Comment by lucasmarques4linux** [comment]
@gnumoksha Eu trabalho no Vila Mariana.. pra mim o bom seria aqui por perto haha..

**Comment by gnumoksha** [comment]
@lucasmarques4linux sim, sim. É só que hoje (literalmente) eu não posso decidir local ainda.
BTW, te mandei mensagem no facebook.

**Comment by lucasmarques73** [comment]
Estou morando em SP..
